### ISSUE TITLE
After dealing with 3 cards, the text reads "Run Away"

### ISSUE THREAD

**Issue by mimshwright** [aliceffekt/Donsol#3]
According to the guide...

> Once you have dealt with at least 3 cards, you can move onto the next room(set of 4 cards), moving the remainder card to the bottom of the deck.
> Running away from the room moves the cards to the bottom of the deck. You can run away from a room you have not interacted with, once in a row.

However, when playing the game, the option is "Run Away" instead of "Enter Room N"

**Comment by mimshwright** [comment]
Incidentally, this also prevents you from running away again because [user escaped] == 1

**Comment by mimshwright** [comment]
Still an issue in 1.2. At least, it's a little confusing that it's not a separate action to run after drawing 3 cards.

**Comment by neauoire** [comment]
What single-word action should I replace the RUN with?
Abandon? Leave? Skip? 

I will use skip for now.

**Comment by JOHNETERNAL** [comment]
If it didn't have to be one word, I would suggest "Move On". 
What about "Next"?
I also like "Abandon"

**Comment by JOHNETERNAL** [comment]
or perhaps "Delve"

**Comment by mimshwright** [comment]
"Pass" is probably my pick. 

Or

"Escape"
"Continue"

Mims H. Wright

Software Engineer

http://mimswright.com

@mimshwright

**Comment by neauoire** [comment]
I'll use PASS

**Comment by JOHNETERNAL** [comment]
In 1.3 when you have dealt with 3 cards you can "run" to the next room, but you are unable to skip as it tells the user "You may not run away twice in a row. 

Moving on from the 3 cards should not count as a skip.

**Comment by neauoire** [comment]
![ios simulator screen shot may 3 2015 10 15 20 am](https://cloud.githubusercontent.com/assets/1455726/7445363/5301557e-f17d-11e4-892e-9a858044a4ac.png)
