### ISSUE TITLE
Attacking same level monster breaks shield

### ISSUE THREAD

**Issue by mimshwright** [aliceffekt/Donsol#4]
When a shield is equipped, if you attack 2 monsters with exactly the same value in a row, your shield will break and you will see the message "Attacking increasingly harder monsters, with the same shield, will break it."
It should say something like...
"Attacking monsters with the same or greater strength using the same shield will break it."
Or it should not break.

**Comment by neauoire** [comment]
Thanks, I will update the manual and modal : )

**Comment by neauoire** [comment]
Pushed
