### ISSUE TITLE
Leaving a dungeon (before dying) doesn't reset your AP

### ISSUE THREAD

**Issue by mimshwright** [aliceffekt/Donsol#5]
If you go into a dungeon and collect a shield, then "Leave Dungeon" and "Enter Dungeon" your AP will be the same as before you left.

**Comment by neauoire** [comment]
This was fixed in the 1.2 update.

**Comment by mimshwright** [comment]
Is the latest in GitHub or do you have a separate code base?

**Comment by mimshwright** [comment]
Nevermind. i just needed to pull.
